pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=2"
    conditions:
      - base=master
      - head=develop
    actions:
      merge:
        method: merge
