spring:
  application:
    name: trabalho-edsII
  profiles:
    active: ${ENVIRONMENT}

server:
  port: 8080
  servlet:
    context-path: /trabalho-edsII

management:
  info:
    git:
      mode: full
    build:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    version: '@project.version@'
    name: '@project.name@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    description: '@project.description@'