name: auto-merge-approvals

on:
  pull_request_review:
    branches:
      - develop
    types:
      - submitted
  pull_request:
    branches:
      - develop
    types:
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} != 'develop' ]]; then
            echo "Not the desired base branch. Exiting workflow."
            exit 0
          fi

          if [[ ${{ github.event.pull_request.head.ref }} != 'master' ]]; then
            echo "Not the desired head branch. Exiting workflow."
            exit 0
          fi

      - name: Check if PR meets minimum approvals
        id: check_approvals
        uses: actions/github-script@v6
        with:
          script: |
            const requiredApprovals = 2; // Defina o número mínimo de aprovações necessário
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const approvals = reviews.filter(review => review.state === 'APPROVED');
            const isApproved = approvals.length >= requiredApprovals;
            console.log(`Number of approvals: ${approvals.length}`);
            console.log(`Is approved: ${isApproved}`);
            return isApproved.toString();

      - name: Merge PR
        if: steps.check_approvals.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
