name: auto-merge-approvals

on:
  pull_request_review:
    branches:
      - develop
    types:
      - submitted
  pull_request:
    branches:
      - develop
    types:
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    run: echo ${{ github.event.pull_request.labels.*.name }}
    if: contains(github.event.pull_request.labels.*.name, 'Review required')
    steps:
      - name: merge
        uses: nbrugger-tgm/merge-pr-action@v0.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
